pattern:
- R1
- G3
- B7
- D9
- R5
- B1
- R7
- D5
- G9
- D3
- G5
- R9
- G7
- B5
- G1
- B7
- R5
- D9
- R3
- D5
- B9
- D7
- G5
- D1
- G7
- B5
- R9
- B3
- R5
- G9
- R7
- D5
- R1
- D7
- G5
- B9
- G3
- B5
- D9
- B7
places:
  '1':
  - 0
  - 200
  '2':
  - 95
  - 200
  '3':
  - 200
  - 200
  '4':
  - 0
  - 110
  '5':
  - 85
  - 110
  '6':
  - 200
  - 110
  '7':
  - 0
  - 0
  '8':
  - 90
  - 0
  '9':
  - 200
  - 0
repeats: 50
spool_names:
- R
- G
- B
- D
