pattern:
- R1
- G3
- B2
- R4
- G1
- B3
- R2
- G4
- B1
- R3
- G2
- B4
- R1
- G3
- B2
- R4
- G1
- B3
- R2
- G4
- B1
- R3
- G2
places:
  '1':
  - 0
  - 0
  '2':
  - 20
  - 0
  '3':
  - 20
  - 0
  '4':
  - 40
  - 0
repeats: 5
spool_names:
- R
- G
- B
